# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-space-ingress
  annotations:
    # Time in seconds to wait for a response from the pod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "6000"
    # Time in seconds to wait for data to be sent to the pod
    nginx.ingress.kubernetes.io/proxy-send-timeout: "6000"
    # Time in seconds to establish a connection to the pod
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "6000"
    
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-path: "/"

    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/websocket-services: "router-service"
    
  labels:
    app.kubernetes.io/name: code-space-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: "/api/sandbox"
        pathType: Prefix
        backend:
          service:
            name: sandbox-service
            port:
              number: 80
  - http:
      paths:
      - path: "/api/ai"
        pathType: Prefix
        backend:
          service:
            name: ai-service
            port:
              number: 80

  - http:
      paths:
      - path: "/api/auth"
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 80

  - host: "*.preview.localhost"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: router-service
            port:
              number: 80

  - host: "*.agent.localhost"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: router-service
            port:
              number: 80
     